## Build
FROM golang:1.16-buster AS base

LABEL project="vigia-go"

WORKDIR /app

COPY ./go.mod go.sum ./
RUN go mod download

FROM base AS build_metrics

LABEL app="metrics"

COPY ./cmd ./cmd
COPY ./internal ./internal

RUN go build -o ./build/metrics ./cmd/metrics

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /app

COPY --from=build_metrics /app/build/metrics ./metrics
COPY ./deployments/keys ./deployments/keys

USER nonroot:nonroot

ENTRYPOINT ["/app/metrics"]