## Build
FROM golang:1.16-buster AS base

LABEL project="vigia-go"

WORKDIR /app

COPY ./go.mod go.sum ./
RUN go mod download

FROM base AS build_gravacao

LABEL app="gravacao"

COPY ./cmd ./cmd
COPY ./internal ./internal

RUN go build -o ./build/gravacao ./cmd/gravacao

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /app

COPY --from=build_gravacao /app/build/gravacao ./gravacao
COPY ./deployments/keys ./deployments/keys

USER nonroot:nonroot

ENTRYPOINT ["/app/gravacao"]