// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        v3.18.0
// source: gerencia.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServidorGravacaoId string `protobuf:"bytes,1,opt,name=servidor_gravacao_id,json=servidorGravacaoId,proto3" json:"servidor_gravacao_id,omitempty"`
}

func (x *CheckReq) Reset() {
	*x = CheckReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReq) ProtoMessage() {}

func (x *CheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReq.ProtoReflect.Descriptor instead.
func (*CheckReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{0}
}

func (x *CheckReq) GetServidorGravacaoId() string {
	if x != nil {
		return x.ServidorGravacaoId
	}
	return ""
}

type CheckRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckRes) Reset() {
	*x = CheckRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRes) ProtoMessage() {}

func (x *CheckRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRes.ProtoReflect.Descriptor instead.
func (*CheckRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{1}
}

type MatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VeiculoId  string `protobuf:"bytes,1,opt,name=veiculo_id,json=veiculoId,proto3" json:"veiculo_id,omitempty"`
	RegistroId string `protobuf:"bytes,2,opt,name=registro_id,json=registroId,proto3" json:"registro_id,omitempty"`
}

func (x *MatchReq) Reset() {
	*x = MatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchReq) ProtoMessage() {}

func (x *MatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchReq.ProtoReflect.Descriptor instead.
func (*MatchReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{2}
}

func (x *MatchReq) GetVeiculoId() string {
	if x != nil {
		return x.VeiculoId
	}
	return ""
}

func (x *MatchReq) GetRegistroId() string {
	if x != nil {
		return x.RegistroId
	}
	return ""
}

type MatchRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MatchRes) Reset() {
	*x = MatchRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRes) ProtoMessage() {}

func (x *MatchRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRes.ProtoReflect.Descriptor instead.
func (*MatchRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{3}
}

type ErrorReportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServidorGravacaoId string `protobuf:"bytes,1,opt,name=servidor_gravacao_id,json=servidorGravacaoId,proto3" json:"servidor_gravacao_id,omitempty"`
	ProcessoId         string `protobuf:"bytes,2,opt,name=processo_id,json=processoId,proto3" json:"processo_id,omitempty"`
	RegistroId         string `protobuf:"bytes,3,opt,name=registro_id,json=registroId,proto3" json:"registro_id,omitempty"`
	Error              string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	StoppedProcesso    bool   `protobuf:"varint,5,opt,name=stopped_processo,json=stoppedProcesso,proto3" json:"stopped_processo,omitempty"`
}

func (x *ErrorReportReq) Reset() {
	*x = ErrorReportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorReportReq) ProtoMessage() {}

func (x *ErrorReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorReportReq.ProtoReflect.Descriptor instead.
func (*ErrorReportReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorReportReq) GetServidorGravacaoId() string {
	if x != nil {
		return x.ServidorGravacaoId
	}
	return ""
}

func (x *ErrorReportReq) GetProcessoId() string {
	if x != nil {
		return x.ProcessoId
	}
	return ""
}

func (x *ErrorReportReq) GetRegistroId() string {
	if x != nil {
		return x.RegistroId
	}
	return ""
}

func (x *ErrorReportReq) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ErrorReportReq) GetStoppedProcesso() bool {
	if x != nil {
		return x.StoppedProcesso
	}
	return false
}

type ErrorReportRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ErrorReportRes) Reset() {
	*x = ErrorReportRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorReportRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorReportRes) ProtoMessage() {}

func (x *ErrorReportRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorReportRes.ProtoReflect.Descriptor instead.
func (*ErrorReportRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{5}
}

var File_gerencia_proto protoreflect.FileDescriptor

var file_gerencia_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x22, 0x3c, 0x0a, 0x08, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x30, 0x0a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64,
	0x6f, 0x72, 0x5f, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72,
	0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x49, 0x64, 0x22, 0x0a, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x22, 0x4a, 0x0a, 0x08, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x65, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x49, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x49, 0x64,
	0x22, 0x0a, 0x0a, 0x08, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x22, 0xc5, 0x01, 0x0a,
	0x0e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x30, 0x0a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x61, 0x76,
	0x61, 0x63, 0x61, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x6f, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x74, 0x6f,
	0x70, 0x70, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0f, 0x73, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x32, 0xb5, 0x01, 0x0a, 0x08, 0x47, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x69, 0x61, 0x12, 0x31, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x12, 0x2e, 0x67,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x1a, 0x12, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12,
	0x12, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0b, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x69, 0x61, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x18, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x13,
	0x5a, 0x11, 0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gerencia_proto_rawDescOnce sync.Once
	file_gerencia_proto_rawDescData = file_gerencia_proto_rawDesc
)

func file_gerencia_proto_rawDescGZIP() []byte {
	file_gerencia_proto_rawDescOnce.Do(func() {
		file_gerencia_proto_rawDescData = protoimpl.X.CompressGZIP(file_gerencia_proto_rawDescData)
	})
	return file_gerencia_proto_rawDescData
}

var file_gerencia_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gerencia_proto_goTypes = []interface{}{
	(*CheckReq)(nil),       // 0: gerencia.CheckReq
	(*CheckRes)(nil),       // 1: gerencia.CheckRes
	(*MatchReq)(nil),       // 2: gerencia.MatchReq
	(*MatchRes)(nil),       // 3: gerencia.MatchRes
	(*ErrorReportReq)(nil), // 4: gerencia.ErrorReportReq
	(*ErrorReportRes)(nil), // 5: gerencia.ErrorReportRes
}
var file_gerencia_proto_depIdxs = []int32{
	0, // 0: gerencia.Gerencia.Check:input_type -> gerencia.CheckReq
	2, // 1: gerencia.Gerencia.Match:input_type -> gerencia.MatchReq
	4, // 2: gerencia.Gerencia.ErrorReport:input_type -> gerencia.ErrorReportReq
	1, // 3: gerencia.Gerencia.Check:output_type -> gerencia.CheckRes
	3, // 4: gerencia.Gerencia.Match:output_type -> gerencia.MatchRes
	5, // 5: gerencia.Gerencia.ErrorReport:output_type -> gerencia.ErrorReportRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gerencia_proto_init() }
func file_gerencia_proto_init() {
	if File_gerencia_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gerencia_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorReportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorReportRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gerencia_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gerencia_proto_goTypes,
		DependencyIndexes: file_gerencia_proto_depIdxs,
		MessageInfos:      file_gerencia_proto_msgTypes,
	}.Build()
	File_gerencia_proto = out.File
	file_gerencia_proto_rawDesc = nil
	file_gerencia_proto_goTypes = nil
	file_gerencia_proto_depIdxs = nil
}
