// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        v3.18.0
// source: gravacao.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrarReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServidorGravacaoId string `protobuf:"bytes,1,opt,name=servidor_gravacao_id,json=servidorGravacaoId,proto3" json:"servidor_gravacao_id,omitempty"`
	Armazenamento      string `protobuf:"bytes,2,opt,name=armazenamento,proto3" json:"armazenamento,omitempty"`
	HorasRetencao      int32  `protobuf:"varint,3,opt,name=horas_retencao,json=horasRetencao,proto3" json:"horas_retencao,omitempty"`
	EnderecoIp         string `protobuf:"bytes,4,opt,name=endereco_ip,json=enderecoIp,proto3" json:"endereco_ip,omitempty"`
	Porta              int32  `protobuf:"varint,5,opt,name=porta,proto3" json:"porta,omitempty"`
	DbHost             string `protobuf:"bytes,6,opt,name=db_host,json=dbHost,proto3" json:"db_host,omitempty"`
	DbUser             string `protobuf:"bytes,7,opt,name=db_user,json=dbUser,proto3" json:"db_user,omitempty"`
	DbPassword         string `protobuf:"bytes,8,opt,name=db_password,json=dbPassword,proto3" json:"db_password,omitempty"`
	DbName             string `protobuf:"bytes,9,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	DbMaxIdleConns     int32  `protobuf:"varint,10,opt,name=db_max_idle_conns,json=dbMaxIdleConns,proto3" json:"db_max_idle_conns,omitempty"`
	DbMaxOpenConns     int32  `protobuf:"varint,11,opt,name=db_max_open_conns,json=dbMaxOpenConns,proto3" json:"db_max_open_conns,omitempty"`
	DbDisableTls       bool   `protobuf:"varint,12,opt,name=db_disable_tls,json=dbDisableTls,proto3" json:"db_disable_tls,omitempty"`
}

func (x *RegistrarReq) Reset() {
	*x = RegistrarReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrarReq) ProtoMessage() {}

func (x *RegistrarReq) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrarReq.ProtoReflect.Descriptor instead.
func (*RegistrarReq) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrarReq) GetServidorGravacaoId() string {
	if x != nil {
		return x.ServidorGravacaoId
	}
	return ""
}

func (x *RegistrarReq) GetArmazenamento() string {
	if x != nil {
		return x.Armazenamento
	}
	return ""
}

func (x *RegistrarReq) GetHorasRetencao() int32 {
	if x != nil {
		return x.HorasRetencao
	}
	return 0
}

func (x *RegistrarReq) GetEnderecoIp() string {
	if x != nil {
		return x.EnderecoIp
	}
	return ""
}

func (x *RegistrarReq) GetPorta() int32 {
	if x != nil {
		return x.Porta
	}
	return 0
}

func (x *RegistrarReq) GetDbHost() string {
	if x != nil {
		return x.DbHost
	}
	return ""
}

func (x *RegistrarReq) GetDbUser() string {
	if x != nil {
		return x.DbUser
	}
	return ""
}

func (x *RegistrarReq) GetDbPassword() string {
	if x != nil {
		return x.DbPassword
	}
	return ""
}

func (x *RegistrarReq) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *RegistrarReq) GetDbMaxIdleConns() int32 {
	if x != nil {
		return x.DbMaxIdleConns
	}
	return 0
}

func (x *RegistrarReq) GetDbMaxOpenConns() int32 {
	if x != nil {
		return x.DbMaxOpenConns
	}
	return 0
}

func (x *RegistrarReq) GetDbDisableTls() bool {
	if x != nil {
		return x.DbDisableTls
	}
	return false
}

type RegistrarRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegistrarRes) Reset() {
	*x = RegistrarRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrarRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrarRes) ProtoMessage() {}

func (x *RegistrarRes) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrarRes.ProtoReflect.Descriptor instead.
func (*RegistrarRes) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{1}
}

type RemoverRegistroReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoverRegistroReq) Reset() {
	*x = RemoverRegistroReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoverRegistroReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoverRegistroReq) ProtoMessage() {}

func (x *RemoverRegistroReq) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoverRegistroReq.ProtoReflect.Descriptor instead.
func (*RemoverRegistroReq) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{2}
}

type RemoverRegistroRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoverRegistroRes) Reset() {
	*x = RemoverRegistroRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoverRegistroRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoverRegistroRes) ProtoMessage() {}

func (x *RemoverRegistroRes) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoverRegistroRes.ProtoReflect.Descriptor instead.
func (*RemoverRegistroRes) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{3}
}

type StartProcessosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Processos []string `protobuf:"bytes,1,rep,name=processos,proto3" json:"processos,omitempty"`
}

func (x *StartProcessosReq) Reset() {
	*x = StartProcessosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartProcessosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessosReq) ProtoMessage() {}

func (x *StartProcessosReq) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessosReq.ProtoReflect.Descriptor instead.
func (*StartProcessosReq) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{4}
}

func (x *StartProcessosReq) GetProcessos() []string {
	if x != nil {
		return x.Processos
	}
	return nil
}

type StartProcessosRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NonStartedProcessos []string `protobuf:"bytes,1,rep,name=non_started_processos,json=nonStartedProcessos,proto3" json:"non_started_processos,omitempty"`
}

func (x *StartProcessosRes) Reset() {
	*x = StartProcessosRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartProcessosRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessosRes) ProtoMessage() {}

func (x *StartProcessosRes) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessosRes.ProtoReflect.Descriptor instead.
func (*StartProcessosRes) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{5}
}

func (x *StartProcessosRes) GetNonStartedProcessos() []string {
	if x != nil {
		return x.NonStartedProcessos
	}
	return nil
}

type StopProcessosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Processos []string `protobuf:"bytes,1,rep,name=processos,proto3" json:"processos,omitempty"`
}

func (x *StopProcessosReq) Reset() {
	*x = StopProcessosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopProcessosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProcessosReq) ProtoMessage() {}

func (x *StopProcessosReq) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProcessosReq.ProtoReflect.Descriptor instead.
func (*StopProcessosReq) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{6}
}

func (x *StopProcessosReq) GetProcessos() []string {
	if x != nil {
		return x.Processos
	}
	return nil
}

type StopProcessosRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NonStoppedProcessos []string `protobuf:"bytes,1,rep,name=non_stopped_processos,json=nonStoppedProcessos,proto3" json:"non_stopped_processos,omitempty"`
}

func (x *StopProcessosRes) Reset() {
	*x = StopProcessosRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopProcessosRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProcessosRes) ProtoMessage() {}

func (x *StopProcessosRes) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProcessosRes.ProtoReflect.Descriptor instead.
func (*StopProcessosRes) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{7}
}

func (x *StopProcessosRes) GetNonStoppedProcessos() []string {
	if x != nil {
		return x.NonStoppedProcessos
	}
	return nil
}

type ListProcessosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListProcessosReq) Reset() {
	*x = ListProcessosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProcessosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessosReq) ProtoMessage() {}

func (x *ListProcessosReq) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessosReq.ProtoReflect.Descriptor instead.
func (*ListProcessosReq) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{8}
}

type ListProcessosRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessosEmExecucao  []string `protobuf:"bytes,1,rep,name=processos_em_execucao,json=processosEmExecucao,proto3" json:"processos_em_execucao,omitempty"`
	ProcessosEmTentativa []string `protobuf:"bytes,2,rep,name=processos_em_tentativa,json=processosEmTentativa,proto3" json:"processos_em_tentativa,omitempty"`
}

func (x *ListProcessosRes) Reset() {
	*x = ListProcessosRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProcessosRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessosRes) ProtoMessage() {}

func (x *ListProcessosRes) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessosRes.ProtoReflect.Descriptor instead.
func (*ListProcessosRes) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{9}
}

func (x *ListProcessosRes) GetProcessosEmExecucao() []string {
	if x != nil {
		return x.ProcessosEmExecucao
	}
	return nil
}

func (x *ListProcessosRes) GetProcessosEmTentativa() []string {
	if x != nil {
		return x.ProcessosEmTentativa
	}
	return nil
}

type UpdateVeiculosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateVeiculosReq) Reset() {
	*x = UpdateVeiculosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVeiculosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVeiculosReq) ProtoMessage() {}

func (x *UpdateVeiculosReq) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVeiculosReq.ProtoReflect.Descriptor instead.
func (*UpdateVeiculosReq) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{10}
}

type UpdateVeiculosRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateVeiculosRes) Reset() {
	*x = UpdateVeiculosRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVeiculosRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVeiculosRes) ProtoMessage() {}

func (x *UpdateVeiculosRes) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVeiculosRes.ProtoReflect.Descriptor instead.
func (*UpdateVeiculosRes) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{11}
}

type UpdateArmazenamentoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Armazenamento string `protobuf:"bytes,1,opt,name=armazenamento,proto3" json:"armazenamento,omitempty"`
	HorasRetencao int32  `protobuf:"varint,2,opt,name=horas_retencao,json=horasRetencao,proto3" json:"horas_retencao,omitempty"`
}

func (x *UpdateArmazenamentoReq) Reset() {
	*x = UpdateArmazenamentoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArmazenamentoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArmazenamentoReq) ProtoMessage() {}

func (x *UpdateArmazenamentoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArmazenamentoReq.ProtoReflect.Descriptor instead.
func (*UpdateArmazenamentoReq) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateArmazenamentoReq) GetArmazenamento() string {
	if x != nil {
		return x.Armazenamento
	}
	return ""
}

func (x *UpdateArmazenamentoReq) GetHorasRetencao() int32 {
	if x != nil {
		return x.HorasRetencao
	}
	return 0
}

type UpdateArmazenamentoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateArmazenamentoRes) Reset() {
	*x = UpdateArmazenamentoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArmazenamentoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArmazenamentoRes) ProtoMessage() {}

func (x *UpdateArmazenamentoRes) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArmazenamentoRes.ProtoReflect.Descriptor instead.
func (*UpdateArmazenamentoRes) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{13}
}

var File_gravacao_proto protoreflect.FileDescriptor

var file_gravacao_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x22, 0xac, 0x03, 0x0a, 0x0c, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x52, 0x65, 0x71, 0x12, 0x30, 0x0a, 0x14, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x49, 0x64, 0x12, 0x24, 0x0a,
	0x0d, 0x61, 0x72, 0x6d, 0x61, 0x7a, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x72, 0x6d, 0x61, 0x7a, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x6e, 0x74, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x68, 0x6f, 0x72, 0x61, 0x73, 0x5f, 0x72, 0x65, 0x74,
	0x65, 0x6e, 0x63, 0x61, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x68, 0x6f, 0x72,
	0x61, 0x73, 0x52, 0x65, 0x74, 0x65, 0x6e, 0x63, 0x61, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x65, 0x63, 0x6f, 0x5f, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x65, 0x63, 0x6f, 0x49, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x6f, 0x72, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74,
	0x61, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x62, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x62,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x62, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x62, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a,
	0x11, 0x64, 0x62, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x69, 0x64, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x6e,
	0x6e, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x64, 0x62, 0x4d, 0x61, 0x78, 0x49,
	0x64, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x73, 0x12, 0x29, 0x0a, 0x11, 0x64, 0x62, 0x5f, 0x6d,
	0x61, 0x78, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x73, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0e, 0x64, 0x62, 0x4d, 0x61, 0x78, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x6f,
	0x6e, 0x6e, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x64, 0x62, 0x5f, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x5f, 0x74, 0x6c, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x64, 0x62, 0x44,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x6c, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x52, 0x65, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x22,
	0x14, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x31, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x22, 0x47, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x12, 0x32, 0x0a,
	0x15, 0x6e, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x6e, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x73, 0x22, 0x30, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x73, 0x22, 0x46, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x15, 0x6e, 0x6f, 0x6e, 0x5f, 0x73,
	0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x6e, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x70, 0x70,
	0x65, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x22, 0x12, 0x0a, 0x10, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x22,
	0x7c, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73,
	0x52, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x15, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73,
	0x5f, 0x65, 0x6d, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x63, 0x61, 0x6f, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x13, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x45, 0x6d, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x63, 0x61, 0x6f, 0x12, 0x34, 0x0a, 0x16, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x73, 0x5f, 0x65, 0x6d, 0x5f, 0x74, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x76,
	0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x14, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x73, 0x45, 0x6d, 0x54, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x76, 0x61, 0x22, 0x13, 0x0a,
	0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x73, 0x52,
	0x65, 0x71, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x69, 0x63,
	0x75, 0x6c, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x22, 0x65, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x72, 0x6d, 0x61, 0x7a, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x52, 0x65,
	0x71, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x72, 0x6d, 0x61, 0x7a, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x6e,
	0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x72, 0x6d, 0x61, 0x7a, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x68, 0x6f, 0x72, 0x61, 0x73,
	0x5f, 0x72, 0x65, 0x74, 0x65, 0x6e, 0x63, 0x61, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x68, 0x6f, 0x72, 0x61, 0x73, 0x52, 0x65, 0x74, 0x65, 0x6e, 0x63, 0x61, 0x6f, 0x22, 0x18,
	0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x6d, 0x61, 0x7a, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x32, 0xa9, 0x04, 0x0a, 0x08, 0x47, 0x72, 0x61,
	0x76, 0x61, 0x63, 0x61, 0x6f, 0x12, 0x3d, 0x0a, 0x09, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x72, 0x12, 0x16, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x61,
	0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x12, 0x1c, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63,
	0x61, 0x6f, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63,
	0x61, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x73, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e,
	0x53, 0x74, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x70,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x49,
	0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x12,
	0x1a, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x67, 0x72,
	0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x56, 0x65, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x73, 0x12, 0x1b, 0x2e, 0x67, 0x72,
	0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x69,
	0x63, 0x75, 0x6c, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61,
	0x63, 0x61, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x69, 0x63, 0x75, 0x6c,
	0x6f, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x72, 0x6d, 0x61, 0x7a, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x20,
	0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x72, 0x6d, 0x61, 0x7a, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x52, 0x65, 0x71,
	0x1a, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x72, 0x6d, 0x61, 0x7a, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_gravacao_proto_rawDescOnce sync.Once
	file_gravacao_proto_rawDescData = file_gravacao_proto_rawDesc
)

func file_gravacao_proto_rawDescGZIP() []byte {
	file_gravacao_proto_rawDescOnce.Do(func() {
		file_gravacao_proto_rawDescData = protoimpl.X.CompressGZIP(file_gravacao_proto_rawDescData)
	})
	return file_gravacao_proto_rawDescData
}

var file_gravacao_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_gravacao_proto_goTypes = []interface{}{
	(*RegistrarReq)(nil),           // 0: gravacao.RegistrarReq
	(*RegistrarRes)(nil),           // 1: gravacao.RegistrarRes
	(*RemoverRegistroReq)(nil),     // 2: gravacao.RemoverRegistroReq
	(*RemoverRegistroRes)(nil),     // 3: gravacao.RemoverRegistroRes
	(*StartProcessosReq)(nil),      // 4: gravacao.StartProcessosReq
	(*StartProcessosRes)(nil),      // 5: gravacao.StartProcessosRes
	(*StopProcessosReq)(nil),       // 6: gravacao.StopProcessosReq
	(*StopProcessosRes)(nil),       // 7: gravacao.StopProcessosRes
	(*ListProcessosReq)(nil),       // 8: gravacao.ListProcessosReq
	(*ListProcessosRes)(nil),       // 9: gravacao.ListProcessosRes
	(*UpdateVeiculosReq)(nil),      // 10: gravacao.UpdateVeiculosReq
	(*UpdateVeiculosRes)(nil),      // 11: gravacao.UpdateVeiculosRes
	(*UpdateArmazenamentoReq)(nil), // 12: gravacao.UpdateArmazenamentoReq
	(*UpdateArmazenamentoRes)(nil), // 13: gravacao.UpdateArmazenamentoRes
}
var file_gravacao_proto_depIdxs = []int32{
	0,  // 0: gravacao.Gravacao.Registrar:input_type -> gravacao.RegistrarReq
	2,  // 1: gravacao.Gravacao.RemoverRegistro:input_type -> gravacao.RemoverRegistroReq
	4,  // 2: gravacao.Gravacao.StartProcessos:input_type -> gravacao.StartProcessosReq
	6,  // 3: gravacao.Gravacao.StopProcessos:input_type -> gravacao.StopProcessosReq
	8,  // 4: gravacao.Gravacao.ListProcessos:input_type -> gravacao.ListProcessosReq
	10, // 5: gravacao.Gravacao.UpdateVeiculos:input_type -> gravacao.UpdateVeiculosReq
	12, // 6: gravacao.Gravacao.UpdateArmazenamento:input_type -> gravacao.UpdateArmazenamentoReq
	1,  // 7: gravacao.Gravacao.Registrar:output_type -> gravacao.RegistrarRes
	3,  // 8: gravacao.Gravacao.RemoverRegistro:output_type -> gravacao.RemoverRegistroRes
	5,  // 9: gravacao.Gravacao.StartProcessos:output_type -> gravacao.StartProcessosRes
	7,  // 10: gravacao.Gravacao.StopProcessos:output_type -> gravacao.StopProcessosRes
	9,  // 11: gravacao.Gravacao.ListProcessos:output_type -> gravacao.ListProcessosRes
	11, // 12: gravacao.Gravacao.UpdateVeiculos:output_type -> gravacao.UpdateVeiculosRes
	13, // 13: gravacao.Gravacao.UpdateArmazenamento:output_type -> gravacao.UpdateArmazenamentoRes
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_gravacao_proto_init() }
func file_gravacao_proto_init() {
	if File_gravacao_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gravacao_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrarReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrarRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoverRegistroReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoverRegistroRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartProcessosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartProcessosRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopProcessosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopProcessosRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProcessosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProcessosRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVeiculosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVeiculosRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArmazenamentoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArmazenamentoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gravacao_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gravacao_proto_goTypes,
		DependencyIndexes: file_gravacao_proto_depIdxs,
		MessageInfos:      file_gravacao_proto_msgTypes,
	}.Build()
	File_gravacao_proto = out.File
	file_gravacao_proto_rawDesc = nil
	file_gravacao_proto_goTypes = nil
	file_gravacao_proto_depIdxs = nil
}
